# Generated by Django 5.2.1 on 2025-05-19 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDifficulty',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academic_analytics.course')),
                ('difficulty_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_percentage', models.IntegerField()),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('course_instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.instructor')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.student'),
        ),
    ]
