# Generated by Django 5.2.1 on 2025-05-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='enroll',
            field=models.ForeignKey(db_column='enroll_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enroll',
            field=models.ForeignKey(db_column='enroll_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.enrollment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department'),
        ),
        migrations.AlterField(
            model_name='coursedifficulty',
            name='course',
            field=models.OneToOneField(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academic_analytics.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.course'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='instructor',
            field=models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.instructor'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='semester',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='stu',
            field=models.ForeignKey(db_column='stu_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.student'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dept',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.department'),
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='assessment',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendance',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursedifficulty',
            table='course_difficulty',
        ),
        migrations.AlterModelTable(
            name='courseinstructor',
            table='course_instructor',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='instructor',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semester',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
