# Generated by Django 5.2.1 on 2025-05-20 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_analytics', '0002_alter_assessment_enroll_alter_attendance_enroll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSemester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.course')),
                ('semester', models.ForeignKey(db_column='semester_id', on_delete=django.db.models.deletion.CASCADE, to='academic_analytics.semester')),
            ],
            options={
                'db_table': 'academic_analytics_coursesemester',
                'constraints': [models.UniqueConstraint(fields=('course', 'semester'), name='unique_course_semester')],
            },
        ),
    ]
